export enum VaultState {
  LOCKED,
  UNLOCKED,
}

export enum MainMenuOptions {
  LIST_CREDENTIALS,
  STORE_CREDENTIAL,
  COPY_SECRET_CLIPBOARD,
  REMOVE_CREDENTIAL,
  GENERATE_PASSWORD,
  SHOW_LAST_GENERATED_PASSWORD,
  SHOW_CREDENTIAL,
  UPDATE_VAULT_PASSWORD,
  EXIT,
}
