export enum VaultState {
  LOCKED,
  UNLOCKED,
}

export enum MainMenuOptions {
  LIST_CREDENTIALS = 'LIST_CREDENTIALS',
  STORE_CREDENTIAL = 'STORE_CREDENTIAL',
  COPY_SECRET_CLIPBOARD = 'COPY_SECRET_CLIPBOARD',
  REMOVE_CREDENTIAL = 'REMOVE_CREDENTIAL',
  GENERATE_PASSWORD = 'GENERATE_PASSWORD',
  SHOW_LAST_GENERATED_PASSWORD = 'SHOW_LAST_GENERATED_PASSWORD',
  SHOW_CREDENTIAL = 'SHOW_CREDENTIAL',
  UPDATE_VAULT_PASSWORD = 'UPDATE_VAULT_PASSWORD',
  BACKUP_VAULT = 'BACKUP_VAULT',
  EXIT = 'EXIT',
}
